name: Build and Publish Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz

      - name: Generate Documentation
        run: doxygen docs/Doxyfile

      - name: Publish Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages