name: basic                        # собрать и запустить
on: [push]                         # в какой момент запускать (в данном случае при вызове push)
jobs:                              # словарь
  build:                           # ключ
    runs-on: ubuntu-latest         # значение
    steps:                         # этапы
      -uses: actions/checkout@v4   # файл из репозитория загрузить на машину
      -run: g++ main.cpp func.cpp -o main
      -run: ./main 4 6