name: basic

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install -y cmake g++
    - run: mkdir build && cmake -B build -S . && cmake --build build && ls build
    - uses: actions/upload-artifact@v4
      with:
        name: binaries
        path: |
          build/main
          build/tests
          build/benchmarks  # Добавляем бенчмарки

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries
    - run: chmod +x tests && ./tests

  run:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries
    - run: chmod +x main && ./main 2 7

  benchmarks:  # Новый job для бенчмарков
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: binaries
    - run: chmod +x benchmarks && ./benchmarks